print("================================")
print("= NAMA    : DENAS ARIA PAMUNGKAS")
print("= NIM     : 312010076           ")
print("= KELAS   : TI.20 A.1           ")
print("================================")

print("Please enter your full name : DENAS ARIA PAMUNGKAS ")
fullname=input()
print("Please enter nickname : DENAS")
nickname=input()
print("Please enter your NPM : 312010089")
npm=input()
print("Please enter place of birth : BEKASI")
pob=input()
print("Please enter date of birth : 11 ")
date=input()
print("Please enter your month of birth : OCTOBER")
month=input()
print("Please enter year of birth : 2002")
year=input()
print("Please enter your phone number : 085351106660")
phone=input()
print("Please enter your address : Kp.Baru Rengas Bandung")
address=input()

dob=input("2020-year")

print("\n\n Assalamu'alaikum.")
print("Let me introduce my self, my name is {DENAS ARIA PAMUNGKAS}, but you can call me {DENAS}, my NPM {312010089}, I was born in {BEKASI} and iam {2020} years old, I am very glad if you want to invite my house in {Kp.Baru Rengas Bandung}, So don't forget to call me before with the number {085351106660}, \n\n Thanks you ")